# Generated by Django 4.0 on 2022-01-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sap_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('personal_email', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('year_joined', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentt', to='auth.user')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
