# Generated by Django 4.0.3 on 2022-03-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_document_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
    ]
