# Generated by Django 4.0 on 2022-01-26 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('personal_email', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
                ('year_joined', models.DateField(null=True)),
                ('year_passed', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'alumni',
            },
        ),
        migrations.CreateModel(
            name='Placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_profile', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=10, null=True)),
                ('ctc', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('alumnus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
            ],
            options={
                'db_table': 'placements',
            },
        ),
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=10, null=True)),
                ('stipend', models.CharField(max_length=10, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('alumnus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
            ],
            options={
                'db_table': 'internships',
            },
        ),
        migrations.CreateModel(
            name='HigherStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=10, null=True)),
                ('start_year', models.DateField(null=True)),
                ('end_year', models.DateField(null=True)),
                ('alumnus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni')),
            ],
            options={
                'db_table': 'higher_studies',
            },
        ),
    ]
