# Generated by Django 4.0.3 on 2022-03-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_alumni_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placements',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='placements',
            name='job_profile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
