# Generated by Django 4.0.3 on 2022-03-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
